20_MvcCoreUtilidades/Controllers/CachingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace _20_MvcCoreUtilidades.Controllers
{
    public class CachingController : Controller
    {

        private IMemoryCache memoryCache;

        public CachingController(IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache;
        }

        //LA DURACION ESTA ESTABLECIDA EN SEGUNDOS
        [ResponseCache(Duration = 15, Location = ResponseCacheLocation.Client)]
        public IActionResult MemoriaDistribuida()
        {
            string fecha = DateTime.Now.ToLongDateString() + " -- " + DateTime.Now.ToLongTimeString();

            ViewData["FECHA"] = fecha;

            return View();
        }

        public IActionResult MemoriaPersonalizada(int? tiempo)
        {

            if(tiempo == null)
            {
                //PONEMOS EL ALMACEN DURANTE 60 SEGUNDOS LA PRIMERA VEZ
                tiempo = 5;
            }

            string fecha = DateTime.Now.ToLongDateString() + " -- " + DateTime.Now.ToLongTimeString();

            if(this.memoryCache.Get("FECHA") == null)
            {
                //NO EXISTE CACHE
                //CREAMOS LAS OPCIONES DE DURACION DEL CACHE
                MemoryCacheEntryOptions options = new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromSeconds(tiempo.Value));

                //CONFIGURAMOS EL TIEMPO AL GENERAR EL CACHE
                this.memoryCache.Set("FECHA", fecha, options);

                ViewData["MENSAJE"] = "Almacenando en cache";
                ViewData["FECHA"] = this.memoryCache.Get("FECHA");
            } else
            {
                //TENEMOS UN OBJETO EN CLASE
                fecha = this.memoryCache.Get<string>("FECHA");

                ViewData["MENSAJE"] = "Recuperando cache";
                ViewData["FECHA"] = fecha;
            }

            return View();
        }
    }
}

20_MvcCoreUtilidades/Views/Caching/MemoriaDistribuida.cshtml
<h1>Memeoria distribuida</h1>


<a asp-controller="Caching" asp-action="MemoriaDistribuida">Actualizar</a>


<h1 style="color:blue">@ViewData["FECHA"]</h1>

20_MvcCoreUtilidades/Views/Caching/MemoriaPersonalizada.cshtml
<h1>Memoria personalizada caching</h1>


<a asp-controller="Caching" asp-action="MemoriaPersonalizada" asp-route-tiempo="15">Actualizar pagina 15 segundos</a>

<a asp-controller="Caching" asp-action="MemoriaPersonalizada" asp-route-tiempo="30">Actualizar pagina 30 segundos</a>

<h1 style="color:red">@ViewData["MENSAJE"]</h1>

<h1 style="color:blue">@ViewData["FECHA"]</h1>