20_MvcCoreUtilidades/Controllers/CifradosController.cs
using _20_MvcCoreUtilidades.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace _20_MvcCoreUtilidades.Controllers
{
    public class CifradosController : Controller
    {
        public IActionResult CifradoBasico()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoBasico(string contenido, string resultado, string accion)
        {
            //CIFRAMOS EL CONTENIDO CON EL HELPER
            string response = HelperCryptography.EncriptarTextoBasico(contenido);

            if(accion.ToLower() == "cifrar")
            {
                ViewData["TEXTOCIFRADO"] = response;
            } else if (accion.ToLower() == "comparar")
            {
                //COMPARAMOS EL CONTENIDO CIFRADO CON EL RESULTADO DE LA CAJA
                if(response != resultado)
                {
                    ViewData["MENSAJE"] = "Los valores no coinciden";
                } else
                {
                    ViewData["MENSAJE"] = "Contenidos iguales";
                }
            }

            return View();
        }


        public IActionResult CifradoEficiente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoEficiente(string contenido, string resultado, string accion)
        {
            if(accion.ToLower() == "cifrar")
            {
                //LO QUE HAREMOS SERA GUARDAR EL SALT GENERADO
                string response = HelperCryptography.EncriptarContenido(contenido, false);

                ViewData["TEXTOCIFRADO"] = response;
            } else if(accion.ToLower() == "comparar")
            {
                string response = HelperCryptography.EncriptarContenido(contenido, true);

                if(response != resultado)
                {
                    ViewData["MENSAJE"] = "<h1 style='color:blue'>No son iguales</h1>";
                } else
                {
                    ViewData["MENSAJE"] = "<h1 style='color:blue'>Son iguales!!!!</h1>";
                }
            }
            return View();
        }
    }
}

20_MvcCoreUtilidades/Controllers/CochesController.cs
using _20_MvcCoreUtilidades.Models;
using Microsoft.AspNetCore.Mvc;

namespace _20_MvcCoreUtilidades.Controllers
{
    public class CochesController : Controller
    {
        private List<Coche> Cars;
        
        public CochesController()
        {
            this.Cars = new List<Coche>
            {
                new Coche
                {
                    IdCoche = 1, Marca = "Mazda", Modelo = "RX-8", Imagen = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.motor1.com%2Fimages%2Fmgl%2FjEA01%2Fs1%2F2012-353350-mazda-rx-8-blacknight-coupe-project1.jpg&f=1&nofb=1&ipt=3921351a989247a75f1282d2a9b953329dd301aee2c3afbe5834aef03123f82f&ipo=images"
                },
                new Coche
                {
                    IdCoche = 2, Marca = "Nissan", Modelo = "Skyline", Imagen = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F2.bp.blogspot.com%2F-Uhbey2aBHKE%2FUptWUtY6FoI%2FAAAAAAAAItA%2FNcg05Z0iz7M%2Fs1600%2F2014-Nissan-skyline-R34-3-1024X768-Wallpaper.jpg&f=1&nofb=1&ipt=85efc141c77627eda21c71847eba124e935860245270c9ef63c13f28d458fb3f&ipo=images"
                },
                new Coche
                {
                    IdCoche = 3, Marca = "Toyota", Modelo = "Supra", Imagen = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fw-dog.ru%2Fwallpapers%2F0%2F11%2F347259610908269.jpg&f=1&nofb=1&ipt=51d06f00cbea3aabf4261506986356218adea2dcc5a81c8e704767c2193c69c6&ipo=images"
                },
                new Coche
                {
                    IdCoche = 4, Marca = "Ford", Modelo = "Mustang Shelby", Imagen = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.carscoops.com%2Fwp-content%2Fuploads%2F2019%2F09%2F3f2ff3ff-ford-mustang-shelby-gt500.jpg&f=1&nofb=1&ipt=cb8a2089c433f8f27cd64ce60f8b8c35c9e61bdf583fa9db0a5ff213455a878e&ipo=images"
                },
            };
        }

        public IActionResult Index()
        {
            return View();
        }

        //NECESITAMOS UNA PETICION PARA CADA VISTA ASINCRONA QUE VAMOS A UTILIZAR
        //LOS METODOS PUEDEN LLAMARSE COMO QUERMOS, ES DECIR, DIFERENTES A LOS NOMBRES DE LAS VISTAS QUE UTILIZAN
        public IActionResult _CochesPartial()
        {
            //SI VAMOS A UTILIZAR UNA VISTA PARCIAL CON AJAX DEVEMOS DEVOLVER PARTIALVIEW
            //DEBE TENER EL NOMBRE DE LA VISTA PARCIAL Y EL MODEL SI LO NECESITAMOS
            return PartialView("_CochesPartial", this.Cars);
        }


        //SI ESTAMOS UTIILIZANDO PARTIAL VIEW, SOLAMENTE PODEMOS RECIBIR PRIMITIVOS
        public IActionResult _DetailsCoches(int idCoche)
        {
            Coche car = this.Cars.FirstOrDefault(x => x.IdCoche == idCoche);
            return PartialView("_DetailsCoches", car);
        }
    }
}

20_MvcCoreUtilidades/Controllers/MailsController.cs
using _20_MvcCoreUtilidades.Helpers;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace _20_MvcCoreUtilidades.Controllers
{
    public class MailsController : Controller
    {

        private HelperUploadFiles helperUploadFiles;
        private HelperMail helperMail;

        public MailsController(HelperUploadFiles helperUploadFiles, HelperMail helperMail)
        {
            this.helperUploadFiles = helperUploadFiles;
            this.helperMail = helperMail;
        }


        public IActionResult SendMail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMail
    (string para, string asunto, string mensaje
    , List<IFormFile> files)
        {
            if (files.Count != 0)
            {
                if (files.Count > 1)
                {
                    List<string> paths =
                        await this.helperUploadFiles.UploadFileAsync
                        (files, Folders.Temporal);
                    await this.helperMail.SendMailAsync(para, asunto, mensaje, paths);
                }
                else
                {
                    string path =
                        await this.helperUploadFiles.UploadFileAsync
                        (files[0], Folders.Temporal);
                    await this.helperMail.SendMailAsync(para, asunto, mensaje, path);
                }
            }
            else
            {
                await this.helperMail.SendMailAsync(para, asunto, mensaje);
            }
            ViewData["MENSAJE"] = "Email enviado correctamente";
            return View();
        }
    }
}

20_MvcCoreUtilidades/Controllers/UploadFilesController.cs
using _20_MvcCoreUtilidades.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace _20_MvcCoreUtilidades.Controllers
{
    public class UploadFilesController : Controller
    {

        private HelperPathProvider helperPath;

        public UploadFilesController(HelperPathProvider helperPath)
        {
            this.helperPath = helperPath;
        }

        public IActionResult SubirFichero()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SubirFichero(IFormFile fichero)
        {
            string fileName = fichero.FileName;

            string path = this.helperPath.MapPath(fileName, Folders.Uploads);

            using (Stream stream = new FileStream(path, FileMode.Create))
            {
                await fichero.CopyToAsync(stream);
            }

            ViewData["MENSAJE"] = "Fichero subido a " + path;
            ViewData["URL"] = "<a href=''>Mi fichero</a>";

            return View();
        }
    }
}

20_MvcCoreUtilidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _20_MvcCoreUtilidades</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_20_MvcCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_20_MvcCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UploadFiles" asp-action="SubirFichero">Subir Fichero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mails" asp-action="SendMail">Enviar email</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrados" asp-action="CifradoBasico">Cifrado basico</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrados" asp-action="CifradoEficiente">Cifrado eficiente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coches" asp-action="Index">Cargar coches Ajax</a>
                        </li>
                        <partial name="_MenuUsuario" />
                        @await Component.InvokeAsync("MenuCoches")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _20_MvcCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

20_MvcCoreUtilidades/Views/Shared/_MenuUsuario.cshtml
@{
    string usuario = Context.Session.GetString("USUARIO");
}

@if(usuario == null)
{
    <li class="nav-item">
        <a asp-controller="Home" asp-action="Login" class="nav-link">Login</a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="Home" asp-action="CerrarSession" class="nav-link">Cerrar sesion</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Comentarios</a>
    </li>

}